import react, { useRef } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { ParallaxProvider, ParallaxBanner } from 'react-scroll-parallax';
import Fade from 'react-reveal/Fade';

const ParallaxHeader = () => {
  const mountains1 = {
    image:
      'mountains1.svg',
    translateY: [27, 45],
    opacity: [1, 1],
    scale: [1.01, 1.01, 'easeOutCubic'],
    shouldAlwaysCompleteAnimation: true,
    className: 'background1'
  };
  const mountains2 = {
    image:
      'mountains2.svg',
    translateY: [21, 50],
    opacity: [1, 1],
    scale: [1.04, 1.04, 'easeOutCubic'],
    shouldAlwaysCompleteAnimation: true,
    className: 'background2'
  };

  const mountains3 = {
    image:
      'mountains3.svg',
    translateY: [21, 52],
    opacity: [1, 1],
    scale: [1.04, 1.08, 'easeOutCubic'],
    shouldAlwaysCompleteAnimation: true,
    className: 'background3'
  };

  const sun = {
    translateY: [60, 55],
    opacity: [1, 1],
    scale: [1.04, 1.04, 'easeOutCubic'],
    shouldAlwaysCompleteAnimation: true,
    className: 'sun',
    children: (
      <div style={{paddingLeft: 100}}><div id="sun"/></div>
    )
  };

  const logo = {
    translateY: [1, 20],
    scale: [0.6, 0.6, 'easeOutCubic'],
    shouldAlwaysCompleteAnimation: true,
    expanded: false,
    children: (
      <div className="">
       <Image src="/logo.png" alt="Valley View HealthCare Services Logo" width={683} height={185} style={{scale: 0.5}} />
      </div>
    ),
  };

  const foreground = {
    image:
      'trees-water2.svg',
    translateY: [3, 4],
    scale: [1.01, 1.01, 'easeOutCubic'],
    shouldAlwaysCompleteAnimation: true,
    className: 'foreground'
  };

  return (
    <ParallaxBanner
      layers={[sun, mountains3, mountains2, mountains1, logo, foreground]}
      className="parallax-container"
    />
  );
};

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ParallaxProvider>
        <ParallaxHeader />
      </ParallaxProvider>

      <section className="main">
        <Fade bottom cascade>
          <div style={{padding: 20, marginTop: '-10px'}}>
            <h1 style={{margin: 'auto'}}>About Us</h1>
            <p style={{fontSize: 18, lineHeight: 1.5}}>Valley View Healthcare Services is a locally owned and operated home health agency. We take pride in helping our community members stay home and healthy by being their advocate between our local hospitals and their physicians.</p>
            <p style={{fontSize: 18, lineHeight: 1.5}}>Valley View Healthcare Services is a locally owned and operated home health agency. We take pride in helping our community members stay home and healthy by being their advocate between our local hospitals and their physicians.</p>
            <p></p>
          </div>
        </Fade>
        <Fade bottom cascade>
          <div style={{padding: 20, borderTop: '1px solid rgba(255,255,255,0.1)'}}>
            <p>Footer</p>
            <a href="">Home</a>
          </div>
        </Fade>
      </section>
    </div>
  )
}
